name: My Composite Action
description: Prints Hello from the action

runs:
  using: "composite"
  steps:
    - name: Say hello
      run: echo "👋 Hello from my composite action! please wrok"
      shell: bash
    - name: konflux-ui-e2e-tests
      uses: ../my-action2