name: Run on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./.github/actions/my-action
